# Generated by Django 5.2.16 on 2026-07-16 18:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_webhook", "0004_alter_webhookevent_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="error",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="event_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="occurred_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
