# Generated by Django 5.1 on 2026-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_webhook", "0006_unique_event_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="attempts",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="delivered_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="last_attempt_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="object_pk",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="resends",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RETRYING", "RETRYING"),
                    ("FAILURE", "FAILURE"),
                    ("SUCCESS", "SUCCESS"),
                    ("INVALID", "INVALID"),
                ],
                default="PENDING",
                editable=False,
                max_length=40,
            ),
        ),
    ]
